### PR TITLE
Fix endpoint session error

### PR DESCRIPTION
**Pull request by daniddelrio**

### CODE REVIEW

**Comment by daniddelrio** [comment]
[Endpoint session error when clicking Add to Calendar](https://trello.com/c/kUyY33tP/45-endpoint-session-error-when-clicking-add-to-calendar)

**Comment by cianlaguesma** [comment]
image

So I launched the server and the client. I went to localhost:3000 and logged in to Google using my obf account cian.laguesma@obf.ateneo.edu. After that, I went to localhost:8000/admin and clicked org hosts, then computer society of the ateneo, then on the dropdown "user" i chose my obf account. I clicked save and went back to localhost:3000 and clicked on my events - > new event. 
added all the fields and clicked submit for approval. Now im on localhost:3000/browse, i clicked read more on an event and clicked add to calendar. An error DoesNotExist at /gcal/events/1 occured.

**Comment by cianlaguesma** [comment]
image

So I launched the server and the client. 
I went to localhost:3000 and logged in to Google using my obf account cian.laguesma@obf.ateneo.edu. 
After that, I went to localhost:8000/admin and clicked org hosts, then computer society of the ateneo, then on the dropdown "user" i chose my obf account.
I clicked save and went back to localhost:3000 and clicked on my events - > new event. 
I added all the fields and clicked submit for approval. 
Now im on localhost:3000/browse, i clicked read more on an event and clicked add to calendar. 
An error DoesNotExist at /gcal/events/1 occured.

**Comment by cianlaguesma** [comment]
it works, approved!!

**Pull request merged**
